CREATE TABLE [dbo].[Employees](
    [EmployeeId] [varchar](10) NOT NULL PRIMARY KEY,
    [Name_FirstName] [nvarchar](100) NULL,
    [Name_MiddleName] [nvarchar](100) NULL,
    [Name_LastName] [nvarchar](100) NULL,
    [Name_FullName] [nvarchar](300) NOT NULL,
    [Salutation] [tinyint] NOT NULL,
    [NickName] [varchar](50) NULL,
    [NationalityId] [varchar](50) NULL,
    [LanguageId] [varchar](50) NULL,
    [Email] [varchar](50) NULL,
    [Gender] [tinyint] NOT NULL,
    [BirthDate] [date] NULL,
    [RowNumber] [int] NOT NULL,
    [CreatedBy] [varchar](50) NOT NULL,
    [CreatedDateTime] [datetime2](7) NOT NULL,
    [ModifiedBy] [varchar](50) NULL,
    [ModifiedDateTime] [datetime2](7) NULL,
    [VersionStamp] [int] NOT NULL,
    [Active] [bit] NOT NULL,
    [Initials] [nvarchar](20) NULL,
    [LocationId] [varchar](10) NULL,
    [Location_Name] [varchar](50) NULL,
    [Office] [varchar](20) NULL,
    [ManagerId] [varchar](10) NULL,
    [Manager_Name] [nvarchar](300) NULL,
    [OrganizationId] [varchar](10) NULL,
    [OrganizationName] [varchar](50) NULL,
    [JobId] [varchar](10) NULL,
    [Job_Description] [varchar](50) NULL,
    [JobTypeId] [varchar](10) NULL,
    [JobType_Description] [varchar](50) NULL,
    [Title] [varchar](50) NULL,
    [ValidFrom] [date] NULL,
    [ValidTo] [date] NULL,
    [Released] [bit] NULL,
    [HiredDate] [date] NULL,
    [TerminatedDate] [date] NULL
);
